### ISSUE TITLE
Releases seem not to contain the SPICE drivers

### ISSUE THREAD

**Issue by ljrk0** [virtio-win/virtio-win-guest-tools-installer#25] opened 2021-12-09 12:26 UTC
The SPICE vdagent from https://www.spice-space.org/download.html seems not to be part of any MSI or ISO image built.  Neither seems the SPICE driver be part of the distribution, although I'm unclear what is meant by that.  AFAIK the vdagent only depends on the some virtio drivers.

**Comment by vrozenfe** [comment] 2021-12-15 03:13
@ljrk0 
Even though that vda agent needs virtio-serial, SPICE is a completely  separate project with its own work-flow.
We do have SPICE vda agent and qxl-dod drivers MSIs embedded  into the bundler (virtio-win-guest-tools.exe) located in the root of virtio-win iso image.

Regards,
Vadim.

**Comment by ljrk0** [comment] 2021-12-15 15:47
Hi @vrozenfe , thank you for your response!

I think I'm mostly confused about whether SPICE is included or not with respect to this note in the README:

> Virtio-win guest tools installer is a msi (Microsoft installer) created with Wix Toolset which installs:
> 
> Spice guest agent and driver - Spice is an open remote computing solution, providing client access to remote machine display and devices, more info on the Offical website.

I've only run the `virtio-win-gt-x64.msi` as I thought that this is part/executed by `virtio-win-guest-tools.exe` and as far as I can tell, `virtio-win-gt-x64.msi` does not contain the SPICE vdagent (and neither QXL DoD?).  However, if these are part of the `virtio-win-guest-tools.exe` then everything is fine.

I think what I'm missing is mostly this:

Suppose I have a Windows VM and want to install everything to support extended QEMU (qemu-agent), virtio, QXL and SPICE.  I'm left a bit confused what I'm supposed to install, according to the documentation.

1. The virtio-win-iso contains `virtio-win-gt-....msi` files which seem to install virtio drivers only.
2. The `virtio-win-guest-tools.exe` seems to contain virtio drivers as cabinet files next to qxl, qemu and spice(?), I suppose?
3. Next to these executables are the drivers in "raw form" as .inf to be loaded e.g., during an installation of the VM.

The README of this project also links to spice-space.org which has its own downloads:

1. spice-guest-tools which contains spice vdagent, QXL and vioserial (however horribly out of date, as it seems)
2. And SPICE WebDAV

Of course you are not responsible for the SPICE project, but since the README links to the page as well as claims that some part of SPICE is included in this installer, it might be helpful to clear this up better.  I'd be glad to volunteer writing the updated documentation, as soon as I myself understand what parts are packaged where :)

Cheers!

**Comment by Remzi1993** [comment] 2022-04-22 16:26
@ljrk0 You only need to download the: Windows guest tools - [spice-guest-tools](https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe) under **Guest**

See: https://www.ctrl.blog/entry/how-to-win10-in-gnome-boxes.html for explaination and instructions.

**Comment by ljrk0** [comment] 2022-10-18 14:23
To be more precise, as you can see here, the downloads are from 2018:

https://www.spice-space.org/download/windows/spice-guest-tools/

**Comment by ljrk0** [comment] 2022-10-18 14:45
Yep, the release is 0.141 which is horribly out of date, c.f.: https://gitlab.freedesktop.org/spice/win32/spice-nsis/-/issues/17

**Comment by ljrk0** [comment] 2022-10-18 15:45
I did some more research, and while I couldn't find the vdagent in the MSI when extracting it, the installation does definitely contain the vd-agent etc. -- as is described in the Makefile.

@vrozenfe: I think part of the confusion is that the documentation is distributed over spice-space.org, the README of this repo, and the README of the https://github.com/virtio-win/virtio-win-pkg-scripts repo.  I propose having one place (this or the virtio-win-pkg-scripts repo) have a proper list of components such as:

> ## Components
>
> * All VirtIO Windows drivers: KVM/QEMU Windows guest drivers for both paravirtual and emulated hardware, more on the [VirtIO KVM Windows Repo](https://github.com/virtio-win/kvm-guest-drivers-windows).
> * SPICE [vd-agent](https://gitlab.freedesktop.org/spice/win32/vd_agent), [QXL](https://gitlab.freedesktop.org/spice/win32/qxl) & [QXL-WDDM-DOD](https://gitlab.freedesktop.org/spice/win32/qxl-wddm-dod) drivers: SPICE is an open remote computing solution, providing client access to remote machine display and devices, more info on the [Offical Website](https://www.spice-space.org/).
> * QEMU Guest Agent: https://gitlab.com/qemu-project/qemu/-/tree/master/qga: Provides the host with the ability to do various administrative tasks on the guest, more details on the [Wiki](https://qemu-project.gitlab.io/qemu/interop/qemu-ga.html).

Ideally with some information what version they pull from where.  The other repository simply links the repository containing that information.

Similarly this part of the README:

> The installer is distributed as part of `virtio-win` package on [Fedora](https://fedorapeople.org/groups/virt/virtio-win/repo/rpms/).

Is duplicated here as well: https://github.com/virtio-win/virtio-win-pkg-scripts#downloads

FWIW, for the current release, I found the following versions:

* SPICE vd-agent: 0.10.0
* SPICE QXL DOD: 0.21 (11/20/2020,10.0.0.21000)
* SPICE QXL: from 2016
* QEMU GA: 104.0.2.0 
* ...

which can be followed from here:
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/virtio-win-pkg-scripts-input/virtio-win-0.1.221-1/

However, it's yet unclear where the QEMU GA binaries come from (and in general, that this contains the GA at all seems undocumented?).

After the documentation has been straightened out, one could ping the people over at SPICE that they maybe simply link to this installer instead as it covers everything the SPICE installer does as well.

**Comment by vrozenfe** [comment] 2022-10-19 01:42
@ljrk0 
Fully agree. The README files need to be updated in synchronised between all virtio-win related projects.
We will sort it out. 
Regarding the origin of QEMU GA binaries - they are coming from our internal build system mostly because the same 
QEMU guest agent binaries are used for building both upstream and downstream (production) virtio-win rpms. 

Best,
Vadim.

**Comment by YanVugenfirer** [comment] 2022-10-19 07:32
@ljrk0 Starting from RHEL9.0 timeline the binaries of  qemu-ga-mingw are originating from the CentOS (and then RHEL) RPMs.

CentOS RPM content can be tracked here: https://gitlab.com/redhat/centos-stream/rpms/mingw-qemu-ga-win

Best regards,
Yan.

**Comment by vrrc** [comment] 2024-04-08 22:59
This still happens with newer relases of the installer. Neither 0.1.248 or 0.1.240 install spice vdagent on Windows 10 or 11. Spice agent is needed in the guest OS for QEMU's "clipboard=vnc" parameter allows copy/paste using noVNC console on Proxmox VE.

**Comment by vrozenfe** [comment] 2024-04-09 04:41
Spice agent is not a part of RHEL virtio-win package anymore. This is the reason why it was removed from the upstream distribution as well, since we are trying to keep the upstream virtio-win package as close to the RHEL virtio-win package
as possible.
Honestly, I don't want to add spice and qxl-dod MSIs back to the bundle. But I can make them a part of ISO and RPM to let the user to install them manually.

Best,
Vadim.

**Comment by vrrc** [comment] 2024-04-10 18:30
Problem is that when upgrading using the ISO from a previous version like 0.1.229 to 0.1.248, the spice agent is removed and the new version has no mention about that the agent isn't installed anymore. IMHO it would be very helpful to both include a message in the installer informing that spice agent is not installed automatically and include the installer in the ISO so it can be easily installed if needed.
Somewhat related to this, there's no mention about this in the [changelog](https://fedorapeople.org/groups/virt/virtio-win/CHANGELOG). Maybe there's some other more deailed changelog that I'm missing?
Thanks!

**Comment by rgl** [comment] 2024-05-09 18:22
FWIW, this is also being mentioned in https://github.com/virtio-win/virtio-win-pkg-scripts/issues/76#issuecomment-2103185076.

**Comment by rgl** [comment] 2024-08-16 11:35
can you please confirm that the spice agent, removed in https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/926dbaca56b03507ecdb6c624e3bb95204f6904a, was re-introduced in https://github.com/virtio-win/virtio-win-pkg-scripts/commit/62c74d124bac4bf8422bf54a97a10702a8f5b938 and included in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.262-2/? if so, maybe this issue can be closed?

**Comment by vrozenfe** [comment] 2024-08-18 00:02
@rgl 

Confirmed.

Vadim.

**Comment by vrozenfe** [comment] 2024-12-04 03:24
Closing this issue as resolved.
Vadim.

**Closed by vrozenfe** 2024-12-04 03:24 UTC
